replicaCount: 1

image:
  repository: ghcr.io/byunjuneseok/commerce-msa-demo-inventory-api
  tag: 25.04.14-develop.0135-a24f13b
  pullPolicy: IfNotPresent

env:
  - name: mysql_datasource_hikari_jdbc_url
    value: jdbc:mysql://mysql-inventory-api-mysql:3306/inventory
  - name: mysql_datasource_hikari_username
    value: inventory
  - name: mysql_datasource_hikari_password
    value: password
  - name: spring_data_redis_host
    value: redis
  - name: spring_data_redis_port
    value: "6379"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
