apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.gateway.port.number }}
        name: {{ .Values.gateway.port.name }}
        protocol: {{ .Values.gateway.port.protocol }}
      tls:
        mode: {{ .Values.gateway.tls.mode }}
        serverCertificate: {{ .Values.gateway.tls.serverCertificate }}
        privateKey: {{ .Values.gateway.tls.privateKey }}
        caCertificates: {{ .Values.gateway.tls.caCertificates }}
      hosts:
        {{- range .Values.gateway.hosts }}
        - {{ . | quote }}
        {{- end }}
