spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: order-api
          uri: ${spring_cloud_gateway_order_api_uri}
          predicates:
            - Path=/order-api/**
          filters:
            - StripPrefix=1

        - id: inventory-api
          uri: ${spring_cloud_gateway_inventory_api_uri}
          predicates:
            - Path=/inventory-api/**
          filters:
            - StripPrefix=1

resilience4j:
  circuitbreaker:
    instances:
      defaultFallback:
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
  timelimiter:
    instances:
      defaultFallback:
        timeoutDuration: 4s