 image:
   repository: arm64v8/mysql
   tag: 8.0

 auth:
   rootPassword: "mysqlroot"
   database: "commercedb"
   username: "commerce"
   password: "commerce123"

 persistence:
   enabled: true
   storageClass: "standard"
   size: 1Gi