auth:
  rootPassword: "root"
  database: "order"
  username: "order"
  password: "password"

persistence:
  enabled: true
  storageClass: "standard"
  size: 1Gi

service:
  type: LoadBalancer
  port: 3306
