auth:
  rootPassword: "mysqlroot"
  database: "commercedb"
  username: "commerce"
  password: "commerce123"

persistence:
  enabled: true
  storageClass: "standard"
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 3306
