name: Delete Old Packages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { app: [
        'service-registry',
        'order-api',
      ] }
    permissions:
      packages: write
    steps:
    - uses: actions/delete-package-versions@v5
      env:
        IMAGE_NAME: "commerce-msa-demo-${{ matrix.app }}"
      with:
        package-name: ${{ env.IMAGE_NAME }}
        package-type: 'container'
        min-versions-to-keep: 0
        delete-only-untagged-versions: 'true'
